apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dks
  labels:
    app.kubernetes.io/instance: devops-knowledge-share 
    app.kubernetes.io/name: devops-knowledge-share
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: devops-knowledge-share 
      app.kubernetes.io/name: devops-knowledge-share
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/instance: devops-knowledge-share 
        app.kubernetes.io/name: devops-knowledge-share
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
