apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dks
  labels:
    app.kubernetes.io/instance: devops-knowledge-share-frontend-service 
    app.kubernetes.io/name: devops-knowledge-share-frontend-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: devops-knowledge-share-frontend 
    app.kubernetes.io/name: devops-knowledge-share-frontend
